"""add scheduling fields to assessment automation

Revision ID: 0baa7e3a50cc
Revises: 6f91d0afd64c
Create Date: 2026-03-21 12:03:38.655902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0baa7e3a50cc'
down_revision: Union[str, None] = '6f91d0afd64c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_automations', sa.Column('is_immediate', sa.Boolean(), nullable=True))
    op.add_column('assessment_automations', sa.Column('send_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessment_automations', 'send_at')
    op.drop_column('assessment_automations', 'is_immediate')
    # ### end Alembic commands ###
