"""Update employees and add departments

Revision ID: 0dd7e1385fff
Revises: 863d2681b72e
Create Date: 2026-03-26 14:58:31.948027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0dd7e1385fff'
down_revision: Union[str, None] = '863d2681b72e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # op.drop_table('ai_simulations')
    # op.drop_table('ai_simulation_interactions')
    # op.drop_table('surveys')
    # op.drop_table('assessment_360_feedbacks')
    # op.drop_table('assessments_360')
    # op.drop_table('survey_responses')
    op.add_column('employees', sa.Column('employee_id', sa.String(length=50), nullable=True))
    op.add_column('employees', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('middle_name', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('employees', sa.Column('mobile', sa.String(length=20), nullable=True))
    op.add_column('employees', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('employees', sa.Column('employment_type', sa.String(length=50), nullable=True))
    op.add_column('employees', sa.Column('hire_date', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('original_hire_date', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('probation_end_date', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('source', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('notice_period', sa.Integer(), nullable=True))
    op.add_column('employees', sa.Column('about_yourself', sa.Text(), nullable=True))
    op.add_column('employees', sa.Column('pan_card_number', sa.String(length=20), nullable=True))
    op.add_column('employees', sa.Column('aadhar_card_number', sa.String(length=20), nullable=True))
    op.add_column('employees', sa.Column('passport_number', sa.String(length=50), nullable=True))
    op.add_column('employees', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('employees', sa.Column('marital_status', sa.String(length=20), nullable=True))
    op.add_column('employees', sa.Column('blood_group', sa.String(length=10), nullable=True))
    op.add_column('employees', sa.Column('address_line_1', sa.String(length=255), nullable=True))
    op.add_column('employees', sa.Column('address_line_2', sa.String(length=255), nullable=True))
    op.add_column('employees', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('pincode', sa.String(length=20), nullable=True))
    op.add_column('employees', sa.Column('department_id', sa.UUID(), nullable=True))
    op.add_column('employees', sa.Column('reporting_to_id', sa.UUID(), nullable=True))
    op.add_column('employees', sa.Column('dependents', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True))
    op.add_column('employees', sa.Column('educational_details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True))
    op.add_column('employees', sa.Column('emergency_contacts', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True))
    op.add_column('employees', sa.Column('social_profiles', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True))
    op.add_column('employees', sa.Column('payment_information', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True))
    op.add_column('employees', sa.Column('roles_responsibilities', sa.Text(), nullable=True))
    op.add_column('employees', sa.Column('skills', postgresql.ARRAY(sa.Text()), nullable=True))
    op.add_column('employees', sa.Column('documents', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True))
    op.alter_column('employees', 'designation',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.create_unique_constraint(None, 'employees', ['email'])
    op.create_unique_constraint(None, 'employees', ['employee_id'])
    op.drop_constraint('employees_user_id_fkey', 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'employees', ['reporting_to_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'employees', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    op.drop_column('employees', 'joined_at')
    op.drop_column('employees', 'department')
    op.drop_column('employees', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('department', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('joined_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key('employees_user_id_fkey', 'employees', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_constraint(None, 'employees', type_='unique')
    op.alter_column('employees', 'designation',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('employees', 'documents')
    op.drop_column('employees', 'skills')
    op.drop_column('employees', 'roles_responsibilities')
    op.drop_column('employees', 'payment_information')
    op.drop_column('employees', 'social_profiles')
    op.drop_column('employees', 'emergency_contacts')
    op.drop_column('employees', 'educational_details')
    op.drop_column('employees', 'dependents')
    op.drop_column('employees', 'reporting_to_id')
    op.drop_column('employees', 'department_id')
    op.drop_column('employees', 'pincode')
    op.drop_column('employees', 'country')
    op.drop_column('employees', 'state')
    op.drop_column('employees', 'city')
    op.drop_column('employees', 'address_line_2')
    op.drop_column('employees', 'address_line_1')
    op.drop_column('employees', 'blood_group')
    op.drop_column('employees', 'marital_status')
    op.drop_column('employees', 'gender')
    op.drop_column('employees', 'date_of_birth')
    op.drop_column('employees', 'passport_number')
    op.drop_column('employees', 'aadhar_card_number')
    op.drop_column('employees', 'pan_card_number')
    op.drop_column('employees', 'about_yourself')
    op.drop_column('employees', 'notice_period')
    op.drop_column('employees', 'source')
    op.drop_column('employees', 'probation_end_date')
    op.drop_column('employees', 'original_hire_date')
    op.drop_column('employees', 'hire_date')
    op.drop_column('employees', 'employment_type')
    op.drop_column('employees', 'phone_number')
    op.drop_column('employees', 'mobile')
    op.drop_column('employees', 'email')
    op.drop_column('employees', 'last_name')
    op.drop_column('employees', 'middle_name')
    op.drop_column('employees', 'first_name')
    op.drop_column('employees', 'employee_id')
    op.drop_table('departments')
    # ### end Alembic commands ###
