"""add_duration_to_interview_automation

Revision ID: 0fdb9ac5355f
Revises: ab1ae2f1e499
Create Date: 2026-03-21 14:28:39.128770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fdb9ac5355f'
down_revision: Union[str, None] = 'ab1ae2f1e499'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_automations', sa.Column('duration', sa.Integer(), server_default='30', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_automations', 'duration')
    # ### end Alembic commands ###
