"""add scheduling fields to mail automation

Revision ID: 1674ce399dd5
Revises: 37171b8b3dd2
Create Date: 2026-03-21 10:49:29.431798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1674ce399dd5'
down_revision: Union[str, None] = '37171b8b3dd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mail_automations', sa.Column('is_immediate', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('mail_automations', sa.Column('send_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mail_automations', 'send_at')
    op.drop_column('mail_automations', 'is_immediate')
    # ### end Alembic commands ###
