"""add google_meet_link to interview_automation

Revision ID: 263f95bdc1ac
Revises: 0fdb9ac5355f
Create Date: 2026-03-21 15:28:20.629342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '263f95bdc1ac'
down_revision: Union[str, None] = '0fdb9ac5355f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_automations', sa.Column('google_meet_link', sa.String(), nullable=True))
    op.alter_column('interview_automations', 'start_date',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using='start_date::date')
    op.alter_column('interview_automations', 'end_date',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using='end_date::date')
    # Handle time_slots transition
    op.add_column('interview_automations', sa.Column('time_slots_new', sa.ARRAY(sa.String()), nullable=True))
    op.execute("UPDATE interview_automations SET time_slots_new = ARRAY(SELECT jsonb_array_elements_text(time_slots)) WHERE time_slots IS NOT NULL AND jsonb_typeof(time_slots) = 'array'")
    op.drop_column('interview_automations', 'time_slots')
    op.alter_column('interview_automations', 'time_slots_new', new_column_name='time_slots')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Downgrade time_slots
    op.add_column('interview_automations', sa.Column('time_slots_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.execute("UPDATE interview_automations SET time_slots_json = to_jsonb(time_slots) WHERE time_slots IS NOT NULL")
    op.drop_column('interview_automations', 'time_slots')
    op.alter_column('interview_automations', 'time_slots_json', new_column_name='time_slots')
    
    op.alter_column('interview_automations', 'end_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
    op.alter_column('interview_automations', 'start_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
    op.drop_column('interview_automations', 'google_meet_link')
    # ### end Alembic commands ###
