"""add_auto_move_to_onboarding_automation

Revision ID: 2ccef0b08eee
Revises: 3e281d646e26
Create Date: 2026-03-24 11:44:45.299696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ccef0b08eee'
down_revision: Union[str, None] = '3e281d646e26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboarding_automations', sa.Column('auto_move', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('onboarding_automations', 'auto_move')
    # ### end Alembic commands ###
