"""Initial migration after single-app refactor

Revision ID: 33626d2d05ac
Revises: 
Create Date: 2026-03-20 12:19:35.014597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33626d2d05ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()

    def drop_index_if_exists(index_name, table_name):
        try:
            op.drop_index(op.f(index_name), table_name=table_name)
        except Exception:
            pass

    def drop_table_if_exists(table_name):
        if table_name in tables:
            op.drop_table(table_name)

    drop_index_if_exists('ix_tenants_org_type', 'tenants')
    drop_index_if_exists('ix_tenants_slug', 'tenants')
    drop_table_if_exists('tenants')
    drop_index_if_exists('ix_automation_rules_tenant_id', 'automation_rules')
    drop_table_if_exists('automation_rules')
    drop_index_if_exists('ix_voice_calls_tenant_id', 'voice_calls')
    drop_index_if_exists('ix_voice_calls_vapi_call_id', 'voice_calls')
    drop_table_if_exists('voice_calls')
    drop_index_if_exists('ix_voice_agent_configs_tenant_id', 'voice_agent_configs')
    drop_table_if_exists('voice_agent_configs')
    
    if 'candidate_applications' in tables:
        drop_index_if_exists('ix_candidate_applications_tenant_id', 'candidate_applications')
        try:
            op.drop_column('candidate_applications', 'tenant_id')
        except Exception:
            pass
    if 'candidates' in tables:
        drop_index_if_exists('ix_candidates_tenant_id', 'candidates')
        try:
            op.drop_constraint(op.f('uq_candidate_tenant_email'), 'candidates', type_='unique')
        except Exception:
            pass
        op.create_unique_constraint(None, 'candidates', ['email'])
        try:
            op.drop_column('candidates', 'tenant_id')
        except Exception:
            pass
            
    if 'companies' in tables:
        drop_index_if_exists('ix_companies_tenant_id', 'companies')
        try:
            op.drop_constraint(op.f('uq_company_tenant_slug'), 'companies', type_='unique')
        except Exception:
            pass
        op.create_unique_constraint(None, 'companies', ['slug'])
        try:
            op.drop_column('companies', 'tenant_id')
        except Exception:
            pass
            
    if 'email_logs' in tables:
        drop_index_if_exists('ix_email_logs_tenant_id', 'email_logs')
        try:
            op.drop_column('email_logs', 'tenant_id')
        except Exception:
            pass
            
    if 'email_templates' in tables:
        drop_index_if_exists('ix_email_templates_tenant_id', 'email_templates')
        try:
            op.drop_column('email_templates', 'tenant_id')
        except Exception:
            pass
            
    if 'enterprise_students' in tables:
        drop_index_if_exists('ix_enterprise_students_tenant_id', 'enterprise_students')
        drop_index_if_exists('ix_enterprise_students_email', 'enterprise_students')
        op.create_index(op.f('ix_enterprise_students_email'), 'enterprise_students', ['email'], unique=True)
        try:
            op.drop_column('enterprise_students', 'tenant_id')
        except Exception:
            pass
            
    if 'hiring_agents' in tables:
        drop_index_if_exists('ix_hiring_agents_tenant_id', 'hiring_agents')
        try:
            op.drop_column('hiring_agents', 'tenant_id')
        except Exception:
            pass
            
    if 'interview_attempts' in tables:
        drop_index_if_exists('ix_interview_attempts_tenant_id', 'interview_attempts')
        try:
            op.drop_column('interview_attempts', 'tenant_id')
        except Exception:
            pass
            
    if 'interview_schedules' in tables:
        drop_index_if_exists('ix_interview_schedules_tenant_id', 'interview_schedules')
        try:
            op.drop_column('interview_schedules', 'tenant_id')
        except Exception:
            pass
            
    if 'interviews' in tables:
        drop_index_if_exists('ix_interviews_tenant_id', 'interviews')
        try:
            op.drop_column('interviews', 'tenant_id')
        except Exception:
            pass
            
    if 'job_postings' in tables:
        drop_index_if_exists('ix_job_postings_tenant_id', 'job_postings')
        try:
            op.drop_column('job_postings', 'tenant_id')
        except Exception:
            pass
            
    if 'job_requirements' in tables:
        drop_index_if_exists('ix_job_requirements_tenant_id', 'job_requirements')
        try:
            op.drop_column('job_requirements', 'tenant_id')
        except Exception:
            pass
            
    if 'mail_automations' in tables:
        drop_index_if_exists('ix_mail_automations_tenant_id', 'mail_automations')
        try:
            op.drop_column('mail_automations', 'tenant_id')
        except Exception:
            pass
            
    if 'roles' in tables:
        drop_index_if_exists('ix_roles_tenant_id', 'roles')
        try:
            op.drop_constraint(op.f('uq_role_tenant_name'), 'roles', type_='unique')
        except Exception:
            pass
        op.create_unique_constraint(None, 'roles', ['name'])
        try:
            op.drop_column('roles', 'tenant_id')
        except Exception:
            pass
            
    if 'users' in tables:
        drop_index_if_exists('ix_users_tenant_id', 'users')
        try:
            op.drop_constraint(op.f('uq_user_tenant_email'), 'users', type_='unique')
        except Exception:
            pass
        op.create_unique_constraint(None, 'users', ['email'])
        try:
            op.drop_column('users', 'tenant_id')
        except Exception:
            pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_user_tenant_email'), 'users', ['tenant_id', 'email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.add_column('roles', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'roles', type_='unique')
    op.create_unique_constraint(op.f('uq_role_tenant_name'), 'roles', ['tenant_id', 'name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_roles_tenant_id'), 'roles', ['tenant_id'], unique=False)
    op.add_column('mail_automations', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_mail_automations_tenant_id'), 'mail_automations', ['tenant_id'], unique=False)
    op.add_column('job_requirements', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_job_requirements_tenant_id'), 'job_requirements', ['tenant_id'], unique=False)
    op.add_column('job_postings', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_job_postings_tenant_id'), 'job_postings', ['tenant_id'], unique=False)
    op.add_column('interviews', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_interviews_tenant_id'), 'interviews', ['tenant_id'], unique=False)
    op.add_column('interview_schedules', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_interview_schedules_tenant_id'), 'interview_schedules', ['tenant_id'], unique=False)
    op.add_column('interview_attempts', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_interview_attempts_tenant_id'), 'interview_attempts', ['tenant_id'], unique=False)
    op.add_column('hiring_agents', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_hiring_agents_tenant_id'), 'hiring_agents', ['tenant_id'], unique=False)
    op.add_column('enterprise_students', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_enterprise_students_email'), table_name='enterprise_students')
    op.create_index(op.f('ix_enterprise_students_email'), 'enterprise_students', ['email'], unique=False)
    op.create_index(op.f('ix_enterprise_students_tenant_id'), 'enterprise_students', ['tenant_id'], unique=False)
    op.add_column('email_templates', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_email_templates_tenant_id'), 'email_templates', ['tenant_id'], unique=False)
    op.add_column('email_logs', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_email_logs_tenant_id'), 'email_logs', ['tenant_id'], unique=False)
    op.add_column('companies', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'companies', type_='unique')
    op.create_unique_constraint(op.f('uq_company_tenant_slug'), 'companies', ['tenant_id', 'slug'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_companies_tenant_id'), 'companies', ['tenant_id'], unique=False)
    op.add_column('candidates', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'candidates', type_='unique')
    op.create_unique_constraint(op.f('uq_candidate_tenant_email'), 'candidates', ['tenant_id', 'email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_candidates_tenant_id'), 'candidates', ['tenant_id'], unique=False)
    op.add_column('candidate_applications', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_candidate_applications_tenant_id'), 'candidate_applications', ['tenant_id'], unique=False)
    op.create_table('voice_agent_configs',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vapi_assistant_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('vapi_phone_number_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('allowed_days', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('start_time', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('end_time', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('timezone', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('max_duration_mins', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_attempts_per_day', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('retry_delay_mins', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('send_link_via', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('job_requirement_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('stage_index', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('stage_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('interview_questions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('retell_agent_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_requirement_id'], ['job_requirements.id'], name=op.f('voice_agent_configs_job_requirement_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('voice_agent_configs_pkey'))
    )
    op.create_index(op.f('ix_voice_agent_configs_tenant_id'), 'voice_agent_configs', ['tenant_id'], unique=False)
    op.create_table('voice_calls',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('application_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vapi_call_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('transcript', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recording_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ended_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('retell_call_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['candidate_applications.id'], name=op.f('voice_calls_application_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('voice_calls_pkey'))
    )
    op.create_index(op.f('ix_voice_calls_vapi_call_id'), 'voice_calls', ['vapi_call_id'], unique=False)
    op.create_index(op.f('ix_voice_calls_tenant_id'), 'voice_calls', ['tenant_id'], unique=False)
    op.create_table('automation_rules',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('round', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('threshold', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('template_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_requirements.id'], name=op.f('automation_rules_job_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['email_templates.id'], name=op.f('automation_rules_template_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('automation_rules_pkey'))
    )
    op.create_index(op.f('ix_automation_rules_tenant_id'), 'automation_rules', ['tenant_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('org_type', postgresql.ENUM('EDUCATION', 'ENTERPRISE', name='org_type'), autoincrement=False, nullable=False),
    sa.Column('db_name', sa.VARCHAR(length=63), autoincrement=False, nullable=True),
    sa.Column('allowed_domains', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('subscription_tier', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('tenants_pkey')),
    sa.UniqueConstraint('db_name', name=op.f('tenants_db_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_index(op.f('ix_tenants_org_type'), 'tenants', ['org_type'], unique=False)
    # ### end Alembic commands ###
