"""add_interviewer_email_and_time_slots_to_interview_automation

Revision ID: 346e5e1c2d83
Revises: 99d76b7c9adc
Create Date: 2026-03-21 14:09:54.456774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '346e5e1c2d83'
down_revision: Union[str, None] = '99d76b7c9adc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_automations', sa.Column('interviewer_email', sa.String(length=255), nullable=True))
    op.add_column('interview_automations', sa.Column('time_slots', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_automations', 'time_slots')
    op.drop_column('interview_automations', 'interviewer_email')
    # ### end Alembic commands ###
