"""add email_template_id to assessment models

Revision ID: 37171b8b3dd2
Revises: d8f854199086
Create Date: 2026-03-20 17:43:11.615862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37171b8b3dd2'
down_revision: Union[str, None] = 'd8f854199086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', postgresql.ENUM('APTITUDE', 'CODING', 'BOTH', name='assessmenttype', create_type=False), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=True),
    sa.Column('generated_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('test_duration', sa.Integer(), nullable=False),
    sa.Column('email_template_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['email_template_id'], ['email_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('assessment_attempts', sa.Column('template_id', sa.UUID(), nullable=True))
    op.alter_column('assessment_attempts', 'automation_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'assessment_attempts', 'assessment_templates', ['template_id'], ['id'], ondelete='SET NULL')
    op.add_column('assessment_automations', sa.Column('email_template_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'assessment_automations', 'email_templates', ['email_template_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assessment_automations', type_='foreignkey')
    op.drop_column('assessment_automations', 'email_template_id')
    op.drop_constraint(None, 'assessment_attempts', type_='foreignkey')
    op.alter_column('assessment_attempts', 'automation_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('assessment_attempts', 'template_id')
    op.drop_table('assessment_templates')
    # ### end Alembic commands ###
