"""add_form_data_and_template_id_to_onboarding

Revision ID: 40ff0bbd1333
Revises: a2d314e2f08d
Create Date: 2026-03-21 17:50:50.712612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40ff0bbd1333'
down_revision: Union[str, None] = 'a2d314e2f08d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboardings', sa.Column('form_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('onboardings', 'form_data')
    # ### end Alembic commands ###
