"""add_ai_interview_fields

Revision ID: 77787dc40809
Revises: e0d0863d315b
Create Date: 2026-03-23 11:30:32.345959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77787dc40809'
down_revision: Union[str, None] = 'e0d0863d315b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_automations', sa.Column('interview_type', sa.String(length=50), server_default='GMEET', nullable=False))
    op.add_column('interview_automations', sa.Column('interview_template_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'interview_automations', 'interviews', ['interview_template_id'], ['id'], ondelete='SET NULL')
    op.add_column('interviews', sa.Column('topic', sa.String(length=255), nullable=True))
    op.add_column('interviews', sa.Column('duration', sa.Integer(), server_default='30', nullable=False))
    op.add_column('interviews', sa.Column('difficulty', sa.String(length=50), nullable=False))
    op.add_column('interviews', sa.Column('require_video', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'require_video')
    op.drop_column('interviews', 'difficulty')
    op.drop_column('interviews', 'duration')
    op.drop_column('interviews', 'topic')
    op.drop_constraint(None, 'interview_automations', type_='foreignkey')
    op.drop_column('interview_automations', 'interview_template_id')
    op.drop_column('interview_automations', 'interview_type')
    # ### end Alembic commands ###
