"""Add assessment automation tables

Revision ID: 83d00891d1ee
Revises: 33626d2d05ac
Create Date: 2026-03-20 14:57:49.475169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83d00891d1ee'
down_revision: Union[str, None] = '33626d2d05ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_applications', 'assessment_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_applications', sa.Column('assessment_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
