"""Add target stage to screening auto

Revision ID: 861e3304c5ad
Revises: 78b8ede16a5c
Create Date: 2026-03-24 14:57:05.799701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '861e3304c5ad'
down_revision: Union[str, None] = '78b8ede16a5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screening_automations', sa.Column('target_stage_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screening_automations', 'target_stage_index')
    # ### end Alembic commands ###
