"""Add Interview Automation

Revision ID: 99d76b7c9adc
Revises: 0b5336d2e261
Create Date: 2026-03-21 13:52:51.060479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99d76b7c9adc'
down_revision: Union[str, None] = '0b5336d2e261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_automations',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('job_requirement_id', sa.UUID(), nullable=False),
    sa.Column('stage_index', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(length=255), nullable=True),
    sa.Column('criteria', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=False),
    sa.Column('end_time', sa.String(length=10), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=False),
    sa.Column('email_template_id', sa.UUID(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_move', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['email_template_id'], ['email_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_requirement_id'], ['job_requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('assessment_automations', 'auto_move',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.add_column('interview_schedules', sa.Column('automation_id', sa.UUID(), nullable=True))
    op.alter_column('interview_schedules', 'interview_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('interview_schedules_application_id_fkey'), 'interview_schedules', type_='foreignkey')
    op.create_foreign_key(None, 'interview_schedules', 'interview_automations', ['automation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'interview_schedules', 'candidate_applications', ['application_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interview_schedules', type_='foreignkey')
    op.drop_constraint(None, 'interview_schedules', type_='foreignkey')
    op.create_foreign_key(op.f('interview_schedules_application_id_fkey'), 'interview_schedules', 'candidate_applications', ['application_id'], ['id'], ondelete='SET NULL')
    op.alter_column('interview_schedules', 'interview_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('interview_schedules', 'automation_id')
    op.alter_column('assessment_automations', 'auto_move',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_table('interview_automations')
    # ### end Alembic commands ###
