"""Set employee fields non-nullable

Revision ID: 9d9f20e88100
Revises: 0dd7e1385fff
Create Date: 2026-03-26 15:06:22.260630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d9f20e88100'
down_revision: Union[str, None] = '0dd7e1385fff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('survey_responses')
    # op.drop_table('assessment_360_feedbacks')
    # op.drop_table('ai_simulations')
    # op.drop_table('ai_simulation_interactions')
    # op.drop_table('assessments_360')
    # op.drop_table('surveys')
    op.alter_column('employees', 'employee_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('employees', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('employees', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('employees', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('employees', 'country',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'country',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('employees', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('employees', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('employees', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('employees', 'employee_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # op.create_table('surveys', ...) 
    # [omitted for brevity, just removing the section]
    pass
    # ### end Alembic commands ###
