"""add form_config to onboarding_templates

Revision ID: a2d314e2f08d
Revises: 2c243824074c
Create Date: 2026-03-21 17:24:55.338716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2d314e2f08d'
down_revision: Union[str, None] = '2c243824074c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboarding_templates', sa.Column('form_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('onboarding_templates', 'form_config')
    # ### end Alembic commands ###
