"""add_date_ranges_to_interview_automation

Revision ID: ab1ae2f1e499
Revises: 346e5e1c2d83
Create Date: 2026-03-21 14:18:26.103055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab1ae2f1e499'
down_revision: Union[str, None] = '346e5e1c2d83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_automations', sa.Column('start_date', sa.String(length=15), nullable=True))
    op.add_column('interview_automations', sa.Column('end_date', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_automations', 'end_date')
    op.drop_column('interview_automations', 'start_date')
    # ### end Alembic commands ###
