"""Add dual scoring and BOTH assessment type

Revision ID: d8f854199086
Revises: 83d00891d1ee
Create Date: 2026-03-20 16:42:01.417407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8f854199086'
down_revision: Union[str, None] = '83d00891d1ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add BOTH to AssessmentType enum
    # Note: ALTER TYPE ... ADD VALUE cannot be executed in a transaction block
    op.execute("COMMIT")
    op.execute("ALTER TYPE assessmenttype ADD VALUE 'BOTH'")
    
    # 2. Add columns to assessment_attempts
    op.add_column('assessment_attempts', sa.Column('aptitude_score', sa.Integer(), nullable=True))
    op.add_column('assessment_attempts', sa.Column('coding_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessment_attempts', 'coding_score')
    op.drop_column('assessment_attempts', 'aptitude_score')
    # Note: Removing enum values is complex in Postgres and usually not done in simple downgrades.
    # ### end Alembic commands ###
