"""fix_onboarding_template_delete_constraint

Revision ID: e0d0863d315b
Revises: 40ff0bbd1333
Create Date: 2026-03-23 10:32:42.580936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0d0863d315b'
down_revision: Union[str, None] = '40ff0bbd1333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('onboardings_template_id_fkey'), 'onboardings', type_='foreignkey')
    op.create_foreign_key(None, 'onboardings', 'onboarding_templates', ['template_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'onboardings', type_='foreignkey')
    op.create_foreign_key(op.f('onboardings_template_id_fkey'), 'onboardings', 'onboarding_templates', ['template_id'], ['id'])
    # ### end Alembic commands ###
