from .activity import ACTIVITY_TYPES, Activity, activity_assignees
from .assessment import AssessmentAttempt, AssessmentAutomation, AssessmentTemplate
from .asset import (
    ASSET_CATEGORIES,
    ASSET_OWNERSHIP,
    ASSET_STATUSES,
    RETURN_CONDITIONS,
    Asset,
    AssetAssignment,
)
from .attendance import (
    ATTENDANCE_SOURCES,
    ATTENDANCE_STATUSES,
    PUNCH_DIRECTIONS,
    REGULARIZATION_STATUSES,
    WORK_MODES,
    AttendanceDay,
    AttendancePunch,
    AttendanceRegularization,
    Shift,
)
from .base import EnterpriseBase
from .candidate import ApplicationStatus, Candidate, CandidateApplication
from .communication import EmailLog, EmailTemplate, MailAutomation
from .company import Company
from .customization import (
    CUSTOM_FIELD_ENTITIES,
    CUSTOM_FIELD_TYPES,
    TAG_ENTITIES,
    CustomFieldDefinition,
    CustomFieldValue,
    Tag,
    tag_assignments,
)
from .employee import Department, Employee
from .expense import (
    ADVANCE_STATUSES,
    CLAIM_STATUSES,
    PAYMENT_METHODS,
    ExpenseAdvance,
    ExpenseCategory,
    ExpenseClaim,
    ExpenseItem,
    ExpensePayment,
)
from .folder import CandidateFolder, CandidateFolderMember
from .guest import GUEST_ACCESS_LEVELS, GUEST_STATUSES, Guest, guest_jobs
from .hiring_agent import HiringAgent
from .interview import Interview, InterviewAttempt, InterviewAutomation, InterviewSchedule
from .job import JobPosting, JobRequirement, JobStatus
from .offboarding import (
    OFFBOARDING_REASONS,
    OFFBOARDING_STATUSES,
    OFFBOARDING_TYPES,
    TASK_CATEGORIES,
    Offboarding,
    OffboardingTask,
)
from .onboarding import (
    Onboarding,
    OnboardingActivity,
    OnboardingAutomation,
    OnboardingDocument,
    OnboardingNote,
    OnboardingStatus,
    OnboardingTask,
    OnboardingTemplate,
)
from .performance import (
    CYCLE_STATUSES,
    OBJECTIVE_LEVELS,
    OBJECTIVE_MEASURES,
    OBJECTIVE_STATUSES,
    REVIEW_STATUSES,
    Objective,
    ObjectiveCheckin,
    ObjectiveTemplate,
    Review,
    ReviewCycle,
)
from .project import Project, project_members
from .requests import (
    CHANGE_STATUSES,
    CHANGEABLE_FIELDS,
    SIGNATURE_MODULES,
    SIGNATURE_STATUSES,
    TICKET_PRIORITIES,
    TICKET_STATUSES,
    ChangeRequest,
    SignatureRequest,
    Ticket,
    TicketCategory,
    TicketComment,
)
from .simulation import SimulationScenario, SimulationSession
from .student import Student
from .survey import SurveyInstance, SurveyInvite, SurveyQuestion, SurveyResponse, SurveyTemplate, SurveyType
from .user_group import UserGroup, user_group_members, user_group_roles
from .user_role import EnterpriseUser
from .x360 import (
    X360AssessmentAssignment,
    X360AssessmentCycle,
    X360AssessmentResponse,
    X360AssessmentTemplate,
    X360EmployeeRaterMap,
    X360Question,
    X360TemplateQuestion,
)

__all__ = [
    "ACTIVITY_TYPES",
    "ADVANCE_STATUSES",
    "ASSET_CATEGORIES",
    "ASSET_OWNERSHIP",
    "ASSET_STATUSES",
    "ATTENDANCE_SOURCES",
    "ATTENDANCE_STATUSES",
    "CHANGEABLE_FIELDS",
    "CHANGE_STATUSES",
    "CLAIM_STATUSES",
    "CUSTOM_FIELD_ENTITIES",
    "CUSTOM_FIELD_TYPES",
    "CYCLE_STATUSES",
    "GUEST_ACCESS_LEVELS",
    "GUEST_STATUSES",
    "OBJECTIVE_LEVELS",
    "OBJECTIVE_MEASURES",
    "OBJECTIVE_STATUSES",
    "OFFBOARDING_REASONS",
    "OFFBOARDING_STATUSES",
    "OFFBOARDING_TYPES",
    "PAYMENT_METHODS",
    "PUNCH_DIRECTIONS",
    "REGULARIZATION_STATUSES",
    "RETURN_CONDITIONS",
    "REVIEW_STATUSES",
    "SIGNATURE_MODULES",
    "SIGNATURE_STATUSES",
    "TAG_ENTITIES",
    "TASK_CATEGORIES",
    "TICKET_PRIORITIES",
    "TICKET_STATUSES",
    "WORK_MODES",
    "Activity",
    "ApplicationStatus",
    "AssessmentAttempt",
    "AssessmentAutomation",
    "AssessmentTemplate",
    "Asset",
    "AssetAssignment",
    "AttendanceDay",
    "AttendancePunch",
    "AttendanceRegularization",
    "Candidate",
    "CandidateApplication",
    "CandidateFolder",
    "CandidateFolderMember",
    "ChangeRequest",
    "Company",
    "CustomFieldDefinition",
    "CustomFieldValue",
    "Department",
    "EmailLog",
    "EmailTemplate",
    "Employee",
    "EnterpriseBase",
    "EnterpriseUser",
    "ExpenseAdvance",
    "ExpenseCategory",
    "ExpenseClaim",
    "ExpenseItem",
    "ExpensePayment",
    "Guest",
    "HiringAgent",
    "Interview",
    "InterviewAttempt",
    "InterviewAutomation",
    "InterviewSchedule",
    "JobPosting",
    "JobRequirement",
    "JobStatus",
    "MailAutomation",
    "Objective",
    "ObjectiveCheckin",
    "ObjectiveTemplate",
    "Offboarding",
    "OffboardingTask",
    "Onboarding",
    "OnboardingActivity",
    "OnboardingAutomation",
    "OnboardingDocument",
    "OnboardingNote",
    "OnboardingStatus",
    "OnboardingTask",
    "OnboardingTemplate",
    "Project",
    "Review",
    "ReviewCycle",
    "Shift",
    "SignatureRequest",
    "SimulationScenario",
    "SimulationSession",
    "Student",
    "SurveyInstance",
    "SurveyInvite",
    "SurveyQuestion",
    "SurveyResponse",
    "SurveyTemplate",
    "SurveyType",
    "Tag",
    "Ticket",
    "TicketCategory",
    "TicketComment",
    "UserGroup",
    "X360AssessmentAssignment",
    "X360AssessmentCycle",
    "X360AssessmentResponse",
    "X360AssessmentTemplate",
    "X360EmployeeRaterMap",
    "X360Question",
    "X360TemplateQuestion",
    "activity_assignees",
    "guest_jobs",
    "project_members",
    "tag_assignments",
    "user_group_members",
    "user_group_roles",
]

# Register payroll models so SQLAlchemy can resolve Employee.salary_structures
# (relationship target "SalaryStructure") whenever the enterprise models load —
# needed by standalone scripts (master_setup.py, db_diag.py) that configure
# mappers without importing the API routers.
import app.models.payroll  # noqa: F401
