import re
import uuid
from datetime import date, datetime
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, field_validator

_HEX_COLOR = re.compile(r"^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$")


class OrganizationOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    name: str
    currency: str
    legal_name: str | None = None
    industry: str | None = None
    contact_email: str | None = None
    contact_phone: str | None = None
    address_line1: str | None = None
    address_line2: str | None = None
    city: str | None = None
    state: str | None = None
    pincode: str | None = None
    country: str = "India"
    pan: str | None = None
    tan: str | None = None
    created_at: datetime
    updated_at: datetime


class OrganizationUpdate(BaseModel):
    """All fields optional — partial update (only provided fields change)."""

    name: str | None = Field(default=None, min_length=1, max_length=160)
    currency: str | None = Field(default=None, min_length=1, max_length=8)
    legal_name: str | None = Field(default=None, max_length=200)
    industry: str | None = Field(default=None, max_length=120)
    contact_email: str | None = Field(default=None, max_length=255)
    contact_phone: str | None = Field(default=None, max_length=32)
    address_line1: str | None = Field(default=None, max_length=200)
    address_line2: str | None = Field(default=None, max_length=200)
    city: str | None = Field(default=None, max_length=120)
    state: str | None = Field(default=None, max_length=120)
    pincode: str | None = Field(default=None, max_length=16)
    country: str | None = Field(default=None, max_length=80)
    pan: str | None = Field(default=None, max_length=10)
    tan: str | None = Field(default=None, max_length=10)


# ---------------------------------------------------------------------------
# Payslip template (Settings → Payslip)
# ---------------------------------------------------------------------------
class PayslipSettings(BaseModel):
    """Canonical shape of a company's payslip customisation, with defaults.

    Stored as JSON on the company; missing keys fall back to these defaults so
    existing companies render exactly as before. ``display_name``/``accent_color``/
    ``footer_note`` of ``None`` mean "use the built-in default" at render time.
    """

    display_name: str | None = Field(default=None, max_length=160)
    logo_url: str | None = Field(default=None, max_length=2048)
    accent_color: str | None = Field(default=None, max_length=7)
    footer_note: str | None = Field(default=None, max_length=300)
    show_employer_contributions: bool = True
    show_tax_block: bool = True
    show_attendance: bool = True
    # When True and an uploaded .docx template exists, payslips are generated by
    # filling that document instead of the built-in layout.
    use_doc_template: bool = False

    @field_validator("accent_color")
    @classmethod
    def _check_color(cls, v: str | None) -> str | None:
        if v in (None, ""):
            return None
        if not _HEX_COLOR.match(v):
            raise ValueError("accent_color must be a hex colour like #2563eb")
        return v.lower()

    @staticmethod
    def from_stored(data: dict[str, Any] | None) -> "PayslipSettings":
        """Build from the company's stored JSON (None/partial -> defaults)."""
        return PayslipSettings(**(data or {}))


class PayslipSettingsOut(PayslipSettings):
    # The actual company name, so the UI can show it as the fallback when no
    # custom display_name is set.
    company_name: str
    # Uploaded-document-template metadata (the bytes are never returned).
    has_doc_template: bool = False
    doc_filename: str | None = None
    # True when the active template was produced by the smart mapping wizard
    # (i.e. an original upload + a saved field mapping exist).
    doc_mapped: bool = False
    # True when the active template actually contains fillable {{ tokens }}. If a
    # template is uploaded but this is False, payslips render the layout with no
    # data — the UI should warn and steer the admin to the mapping wizard.
    doc_has_tokens: bool = False


# ---------------------------------------------------------------------------
# Payslip "smart mapping" wizard (Settings → Payslip)
# ---------------------------------------------------------------------------
class PayslipFieldOption(BaseModel):
    """One mappable payroll field for the wizard's field dropdown."""

    group: str
    key: str  # the docxtpl token, e.g. "employee.name" / "amount.BASIC"
    label: str


class PayslipDocSlot(BaseModel):
    """A detected value-slot in the uploaded document the admin can map."""

    index: int
    kind: str  # "table" | "para"
    label: str  # the recognised label text next to the slot
    context: str  # surrounding text, to help the admin disambiguate
    current: str  # whatever currently sits in the slot (sample value / blank)
    suggested_token: str | None = None  # auto-detected field, or null


class PayslipDocScanOut(BaseModel):
    """Result of scanning an uploaded template: detected slots + the catalogue
    of fields they can be mapped to."""

    filename: str
    slots: list[PayslipDocSlot]
    fields: list[PayslipFieldOption]


class PayslipMappingApply(BaseModel):
    """Confirmed mapping: slot index (as string, from JSON) -> token key. A
    blank/missing value leaves that slot untouched."""

    mapping: dict[str, str] = Field(default_factory=dict)


class PayslipSettingsUpdate(BaseModel):
    """Partial update — only provided fields change."""

    display_name: str | None = Field(default=None, max_length=160)
    logo_url: str | None = Field(default=None, max_length=2048)
    accent_color: str | None = Field(default=None, max_length=7)
    footer_note: str | None = Field(default=None, max_length=300)
    show_employer_contributions: bool | None = None
    show_tax_block: bool | None = None
    show_attendance: bool | None = None
    use_doc_template: bool | None = None

    @field_validator("accent_color")
    @classmethod
    def _check_color(cls, v: str | None) -> str | None:
        if v in (None, ""):
            return None
        if not _HEX_COLOR.match(v):
            raise ValueError("accent_color must be a hex colour like #2563eb")
        return v.lower()


# ---------------------------------------------------------------------------
# Statutory configuration (Settings → Statutory Compliance)
# ---------------------------------------------------------------------------
# Per-company overrides for the flat statutory rates/thresholds the payroll
# engine uses. Defaults mirror the code constants (statutory.py / tax_engine.py)
# so a company with no overrides computes exactly as before. Rates are stored as
# fractions (0.12 = 12%); the UI presents them as percentages. Slab/bracket
# TABLES (PT per-state, TDS income brackets, 80C/80D caps) remain code-defined.
class StatutoryConfig(BaseModel):
    # --- EPF ---
    pf_employee_rate: float = Field(0.12, ge=0, le=1)
    pf_employer_rate: float = Field(0.12, ge=0, le=1)
    pf_wage_ceiling: float = Field(15000, ge=0)
    eps_rate: float = Field(0.0833, ge=0, le=1)
    eps_wage_ceiling: float = Field(15000, ge=0)
    # --- ESI ---
    esi_wage_limit: float = Field(21000, ge=0)
    esi_employee_rate: float = Field(0.0075, ge=0, le=1)
    esi_employer_rate: float = Field(0.0325, ge=0, le=1)
    # --- TDS scalars (slab brackets stay code-defined) ---
    tds_new_rebate_limit: float = Field(1200000, ge=0)
    tds_old_rebate_limit: float = Field(500000, ge=0)
    tds_new_std_deduction: float = Field(75000, ge=0)
    tds_old_std_deduction: float = Field(50000, ge=0)

    @staticmethod
    def from_stored(data: dict[str, Any] | None) -> "StatutoryConfig":
        """Build from the company's stored JSON (None/partial -> defaults)."""
        return StatutoryConfig(**(data or {}))


# ---------------------------------------------------------------------------
# Work calendar (Settings → Statutory Compliance / Timesheets)
# ---------------------------------------------------------------------------
# Drives how the working-day count for a payroll period is derived. When
# `use_calendar_working_days` is on, working_days = calendar days in the period
# minus weekly-offs minus holidays; otherwise the fixed DEFAULT_WORKING_DAYS (30)
# is used. Stored as JSON on the company alongside the statutory config.
_DAY_CODES = {"MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"}


def _normalize_weekly_offs(v: list[str]) -> list[str]:
    """Normalise/validate weekly-off day codes (dedup, uppercase 3-letter)."""
    out: list[str] = []
    for d in v:
        code = str(d).strip().upper()[:3]
        if code not in _DAY_CODES:
            raise ValueError(f"invalid weekly-off day: {d!r}")
        if code not in out:
            out.append(code)
    return out


class WorkCalendarConfig(BaseModel):
    use_calendar_working_days: bool = True
    weekly_offs: list[str] = Field(default_factory=lambda: ["SAT", "SUN"])
    # Segregation of duties: when on, the user who submitted a timesheet cannot
    # also approve it (maker ≠ checker). Off by default so existing single-HR
    # setups are unaffected. Lives here because it governs the attendance
    # workflow surfaced on the Timesheets screen alongside the calendar config.
    enforce_maker_checker: bool = False

    @field_validator("weekly_offs")
    @classmethod
    def _check_days(cls, v: list[str]) -> list[str]:
        return _normalize_weekly_offs(v)

    @staticmethod
    def from_stored(data: dict[str, Any] | None) -> "WorkCalendarConfig":
        """Build from the company's stored JSON (None/partial -> defaults)."""
        raw = data or {}
        keys = ("use_calendar_working_days", "weekly_offs", "enforce_maker_checker")
        sub = {k: raw[k] for k in keys if k in raw}
        return WorkCalendarConfig(**sub)


class WorkCalendarConfigUpdate(BaseModel):
    """Partial update — only provided fields change."""

    use_calendar_working_days: bool | None = None
    weekly_offs: list[str] | None = None
    enforce_maker_checker: bool | None = None

    @field_validator("weekly_offs")
    @classmethod
    def _check_days(cls, v: list[str] | None) -> list[str] | None:
        return None if v is None else _normalize_weekly_offs(v)


class HolidayIn(BaseModel):
    holiday_date: date
    name: str = Field(min_length=1, max_length=160)


class HolidayOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    holiday_date: date
    name: str


class StatutoryConfigUpdate(BaseModel):
    """Partial update — only provided fields change."""

    pf_employee_rate: float | None = Field(default=None, ge=0, le=1)
    pf_employer_rate: float | None = Field(default=None, ge=0, le=1)
    pf_wage_ceiling: float | None = Field(default=None, ge=0)
    eps_rate: float | None = Field(default=None, ge=0, le=1)
    eps_wage_ceiling: float | None = Field(default=None, ge=0)
    esi_wage_limit: float | None = Field(default=None, ge=0)
    esi_employee_rate: float | None = Field(default=None, ge=0, le=1)
    esi_employer_rate: float | None = Field(default=None, ge=0, le=1)
    tds_new_rebate_limit: float | None = Field(default=None, ge=0)
    tds_old_rebate_limit: float | None = Field(default=None, ge=0)
    tds_new_std_deduction: float | None = Field(default=None, ge=0)
    tds_old_std_deduction: float | None = Field(default=None, ge=0)
