"""implement_rbac_system

Revision ID: 12fac4e5a9b3
Revises: 232483bebb92
Create Date: 2026-04-15 10:52:08.271865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12fac4e5a9b3'
down_revision: Union[str, None] = '232483bebb92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Drop existing FKs that depend on tables we are changing
    op.drop_constraint('super_admin_roles_global_role_id_fkey', 'super_admin_roles', type_='foreignkey')
    
    # 2. Drop the tables that are being superseded
    op.drop_table('global_roles')
    
    # 3. Create the new tables
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('action', sa.Enum('create', 'read', 'update', 'delete', 'moderate', 'assign', 'publish', 'submit', 'review', 'attempt', 'generate', 'finalize', name='permissionaction'), nullable=False),
    sa.Column('module', sa.Enum('platform', 'organization', 'jobs', 'candidates', 'assessments', 'interviews', 'onboarding', 'ai_training', 'surveys', 'communications', 'employees', 'billing', 'analytics', name='modulescope'), server_default='platform', nullable=False),
    sa.Column('scope', sa.Enum('own', 'tenant', 'system', name='permissionscope'), server_default='tenant', nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource', 'action', 'module', 'tenant_id', name='uq_permissions_res_act_mod_ten')
    )
    
    # Update existing Roles table structure
    op.add_column('roles', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.add_column('roles', sa.Column('role_rank', sa.Integer(), server_default='10', nullable=False))
    # Note: uq_roles_name_tenant might fail if existing names are not unique per tenant (usually they are unique globally now, which is fine)
    op.drop_constraint('roles_name_key', 'roles', type_='unique')
    op.create_unique_constraint('uq_roles_name_tenant', 'roles', ['name', 'tenant_id'])
    op.create_foreign_key(None, 'roles', 'companies', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_column('roles', 'permissions')

    # Create join tables
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )

    # Update SuperAdmin relationships
    op.add_column('super_admin_roles', sa.Column('role_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'super_admin_roles', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.drop_column('super_admin_roles', 'global_role_id')

    # Minor structural changes to unrelated tables detected by autogenerate
    op.alter_column('simulation_sessions', 'employee_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('users', 'role_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('super_admin_roles', sa.Column('global_role_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'super_admin_roles', type_='foreignkey')
    # op.create_foreign_key('super_admin_roles_global_role_id_fkey', 'super_admin_roles', 'global_roles', ['global_role_id'], ['id'], ondelete='CASCADE')
    op.drop_column('super_admin_roles', 'role_id')
    op.alter_column('simulation_sessions', 'employee_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('roles', sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_constraint('uq_roles_name_tenant', 'roles', type_='unique')
    op.create_unique_constraint('roles_name_key', 'roles', ['name'])
    op.drop_column('roles', 'role_rank')
    op.drop_column('roles', 'tenant_id')
    op.create_table('global_roles',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('is_system', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='global_roles_pkey'),
    sa.UniqueConstraint('name', name='global_roles_name_key')
    )
    op.create_foreign_key('super_admin_roles_global_role_id_fkey', 'super_admin_roles', 'global_roles', ['global_role_id'], ['id'], ondelete='CASCADE')
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
