"""add payroll module tables and columns

Revision ID: 92fd296f5505
Revises: 2efc8164be58
Create Date: 2026-06-22 14:20:04.652729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92fd296f5505'
down_revision: Union[str, None] = '2efc8164be58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add the 'payroll' value to the ModuleScope enum (RBAC). ALTER TYPE ... ADD
    # VALUE must run outside a transaction block.
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE modulescope ADD VALUE IF NOT EXISTS 'payroll'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=160), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_audit_logs_company_id'), 'payroll_audit_logs', ['company_id'], unique=False)
    op.create_index(op.f('ix_payroll_audit_logs_created_at'), 'payroll_audit_logs', ['created_at'], unique=False)
    op.create_table('holidays',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'holiday_date', name='uq_holiday_company_date')
    )
    op.create_index(op.f('ix_holidays_company_id'), 'holidays', ['company_id'], unique=False)
    op.create_index(op.f('ix_holidays_holiday_date'), 'holidays', ['holiday_date'], unique=False)
    op.create_table('leave_types',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('is_paid', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('annual_quota', sa.Numeric(precision=6, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('accrual', sa.String(length=16), server_default='ANNUAL', nullable=False),
    sa.Column('carry_forward_cap', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_leave_type_company_code')
    )
    op.create_index(op.f('ix_leave_types_company_id'), 'leave_types', ['company_id'], unique=False)
    op.create_table('payroll_cycles',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('pay_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='DRAFT', nullable=False),
    sa.Column('totals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_cycles_company_id'), 'payroll_cycles', ['company_id'], unique=False)
    op.create_table('salary_templates',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('pay_frequency', sa.String(length=16), nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('default_deductions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pf_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('pf_cap_at_ceiling', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('pf_wage_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('esi_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('pt_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('tds_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_unique_template_name', 'salary_templates', ['company_id', 'name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_salary_templates_company_id'), 'salary_templates', ['company_id'], unique=False)
    op.create_table('tds_challans',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('financial_year', sa.String(length=9), server_default='2026-27', nullable=False),
    sa.Column('period_month', sa.String(length=7), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('challan_number', sa.String(length=64), nullable=False),
    sa.Column('bsr_code', sa.String(length=16), nullable=True),
    sa.Column('deposit_date', sa.Date(), nullable=False),
    sa.Column('interest', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('penalty', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tds_challans_company_id'), 'tds_challans', ['company_id'], unique=False)
    op.create_table('employee_tax_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('financial_year', sa.String(length=9), server_default='2026-27', nullable=False),
    sa.Column('tax_regime', sa.String(length=8), server_default='NEW', nullable=False),
    sa.Column('declared_80c', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('declared_80d', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('declared_hra_rent', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('declared_home_loan_interest', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('declared_other', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('prev_employer_income', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('prev_employer_tds', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', name='uq_tax_profile_employee')
    )
    op.create_index(op.f('ix_employee_tax_profiles_company_id'), 'employee_tax_profiles', ['company_id'], unique=False)
    op.create_index(op.f('ix_employee_tax_profiles_employee_id'), 'employee_tax_profiles', ['employee_id'], unique=False)
    op.create_table('leave_balances',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('leave_type_id', sa.UUID(), nullable=False),
    sa.Column('financial_year', sa.String(length=7), server_default='2026-27', nullable=False),
    sa.Column('entitled', sa.Numeric(precision=6, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('accrued', sa.Numeric(precision=6, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('used', sa.Numeric(precision=6, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'leave_type_id', 'financial_year', name='uq_leave_balance_emp_type_fy')
    )
    op.create_index(op.f('ix_leave_balances_company_id'), 'leave_balances', ['company_id'], unique=False)
    op.create_index(op.f('ix_leave_balances_employee_id'), 'leave_balances', ['employee_id'], unique=False)
    op.create_index(op.f('ix_leave_balances_leave_type_id'), 'leave_balances', ['leave_type_id'], unique=False)
    op.create_table('leave_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('leave_type_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('days', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('half_day', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='PENDING', nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('requested_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_requests_company_id'), 'leave_requests', ['company_id'], unique=False)
    op.create_index(op.f('ix_leave_requests_employee_id'), 'leave_requests', ['employee_id'], unique=False)
    op.create_index(op.f('ix_leave_requests_leave_type_id'), 'leave_requests', ['leave_type_id'], unique=False)
    op.create_table('payroll_adjustments',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cycle_id'], ['payroll_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_adjustment_cycle_employee', 'payroll_adjustments', ['cycle_id', 'employee_id'], unique=False)
    op.create_index(op.f('ix_payroll_adjustments_company_id'), 'payroll_adjustments', ['company_id'], unique=False)
    op.create_index(op.f('ix_payroll_adjustments_cycle_id'), 'payroll_adjustments', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_payroll_adjustments_employee_id'), 'payroll_adjustments', ['employee_id'], unique=False)
    op.create_table('payslips',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('gross_earnings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_deductions', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_pay', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('lop_days', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('paid_days', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('earnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deductions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('employer_contributions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('statutory', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='PENDING', nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cycle_id'], ['payroll_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id', 'employee_id', name='uq_payslip_cycle_employee')
    )
    op.create_index(op.f('ix_payslips_company_id'), 'payslips', ['company_id'], unique=False)
    op.create_index(op.f('ix_payslips_cycle_id'), 'payslips', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_payslips_employee_id'), 'payslips', ['employee_id'], unique=False)
    op.create_table('salary_structures',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('ctc', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('pay_frequency', sa.String(length=16), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('default_deductions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('lop_days', sa.Numeric(precision=5, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('pf_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('pf_cap_at_ceiling', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('pf_wage_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('esi_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('pt_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('tds_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['salary_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_active_salary_structure', 'salary_structures', ['employee_id'], unique=True, postgresql_where=sa.text('is_active AND deleted_at IS NULL'))
    op.create_index(op.f('ix_salary_structures_company_id'), 'salary_structures', ['company_id'], unique=False)
    op.create_index(op.f('ix_salary_structures_employee_id'), 'salary_structures', ['employee_id'], unique=False)
    op.create_index(op.f('ix_salary_structures_template_id'), 'salary_structures', ['template_id'], unique=False)
    op.create_table('timesheets',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('mode', sa.String(length=16), server_default='ATTENDANCE', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='DRAFT', nullable=False),
    sa.Column('worked_days', sa.Numeric(precision=6, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('lop_days', sa.Numeric(precision=6, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('half_days', sa.Numeric(precision=6, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('total_hours', sa.Numeric(precision=8, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cycle_id'], ['payroll_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id', 'employee_id', name='uq_timesheet_cycle_employee')
    )
    op.create_index(op.f('ix_timesheets_company_id'), 'timesheets', ['company_id'], unique=False)
    op.create_index(op.f('ix_timesheets_cycle_id'), 'timesheets', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_timesheets_employee_id'), 'timesheets', ['employee_id'], unique=False)
    op.create_table('timesheet_entries',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('timesheet_id', sa.UUID(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('day_status', sa.String(length=16), nullable=False),
    sa.Column('hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['timesheet_id'], ['timesheets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timesheet_id', 'entry_date', name='uq_entry_timesheet_date')
    )
    op.create_index('idx_entry_timesheet', 'timesheet_entries', ['timesheet_id'], unique=False)
    op.create_index(op.f('ix_timesheet_entries_company_id'), 'timesheet_entries', ['company_id'], unique=False)
    op.create_index(op.f('ix_timesheet_entries_timesheet_id'), 'timesheet_entries', ['timesheet_id'], unique=False)
    op.add_column('companies', sa.Column('currency', sa.String(length=8), server_default='INR', nullable=False))
    op.add_column('companies', sa.Column('legal_name', sa.String(length=200), nullable=True))
    op.add_column('companies', sa.Column('contact_email', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('contact_phone', sa.String(length=32), nullable=True))
    op.add_column('companies', sa.Column('address_line1', sa.String(length=200), nullable=True))
    op.add_column('companies', sa.Column('address_line2', sa.String(length=200), nullable=True))
    op.add_column('companies', sa.Column('city', sa.String(length=120), nullable=True))
    op.add_column('companies', sa.Column('state', sa.String(length=120), nullable=True))
    op.add_column('companies', sa.Column('pincode', sa.String(length=16), nullable=True))
    op.add_column('companies', sa.Column('country', sa.String(length=80), server_default='India', nullable=False))
    op.add_column('companies', sa.Column('pan', sa.String(length=10), nullable=True))
    op.add_column('companies', sa.Column('tan', sa.String(length=10), nullable=True))
    op.add_column('companies', sa.Column('payslip_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('companies', sa.Column('statutory_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('companies', sa.Column('payslip_doc_template', sa.LargeBinary(), nullable=True))
    op.add_column('companies', sa.Column('payslip_doc_filename', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('payslip_doc_original', sa.LargeBinary(), nullable=True))
    op.add_column('companies', sa.Column('payslip_doc_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('employees', sa.Column('location', sa.String(length=120), nullable=True))
    op.add_column('employees', sa.Column('bank_account_no', sa.String(length=34), nullable=True))
    op.add_column('employees', sa.Column('uan', sa.String(length=20), nullable=True))
    op.add_column('employees', sa.Column('esic_number', sa.String(length=20), nullable=True))
    op.add_column('employees', sa.Column('date_of_joining', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'date_of_joining')
    op.drop_column('employees', 'esic_number')
    op.drop_column('employees', 'uan')
    op.drop_column('employees', 'bank_account_no')
    op.drop_column('employees', 'location')
    op.drop_column('companies', 'payslip_doc_mapping')
    op.drop_column('companies', 'payslip_doc_original')
    op.drop_column('companies', 'payslip_doc_filename')
    op.drop_column('companies', 'payslip_doc_template')
    op.drop_column('companies', 'statutory_settings')
    op.drop_column('companies', 'payslip_settings')
    op.drop_column('companies', 'tan')
    op.drop_column('companies', 'pan')
    op.drop_column('companies', 'country')
    op.drop_column('companies', 'pincode')
    op.drop_column('companies', 'state')
    op.drop_column('companies', 'city')
    op.drop_column('companies', 'address_line2')
    op.drop_column('companies', 'address_line1')
    op.drop_column('companies', 'contact_phone')
    op.drop_column('companies', 'contact_email')
    op.drop_column('companies', 'legal_name')
    op.drop_column('companies', 'currency')
    op.drop_index(op.f('ix_timesheet_entries_timesheet_id'), table_name='timesheet_entries')
    op.drop_index(op.f('ix_timesheet_entries_company_id'), table_name='timesheet_entries')
    op.drop_index('idx_entry_timesheet', table_name='timesheet_entries')
    op.drop_table('timesheet_entries')
    op.drop_index(op.f('ix_timesheets_employee_id'), table_name='timesheets')
    op.drop_index(op.f('ix_timesheets_cycle_id'), table_name='timesheets')
    op.drop_index(op.f('ix_timesheets_company_id'), table_name='timesheets')
    op.drop_table('timesheets')
    op.drop_index(op.f('ix_salary_structures_template_id'), table_name='salary_structures')
    op.drop_index(op.f('ix_salary_structures_employee_id'), table_name='salary_structures')
    op.drop_index(op.f('ix_salary_structures_company_id'), table_name='salary_structures')
    op.drop_index('idx_active_salary_structure', table_name='salary_structures', postgresql_where=sa.text('is_active AND deleted_at IS NULL'))
    op.drop_table('salary_structures')
    op.drop_index(op.f('ix_payslips_employee_id'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_cycle_id'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_company_id'), table_name='payslips')
    op.drop_table('payslips')
    op.drop_index(op.f('ix_payroll_adjustments_employee_id'), table_name='payroll_adjustments')
    op.drop_index(op.f('ix_payroll_adjustments_cycle_id'), table_name='payroll_adjustments')
    op.drop_index(op.f('ix_payroll_adjustments_company_id'), table_name='payroll_adjustments')
    op.drop_index('idx_adjustment_cycle_employee', table_name='payroll_adjustments')
    op.drop_table('payroll_adjustments')
    op.drop_index(op.f('ix_leave_requests_leave_type_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_employee_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_company_id'), table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index(op.f('ix_leave_balances_leave_type_id'), table_name='leave_balances')
    op.drop_index(op.f('ix_leave_balances_employee_id'), table_name='leave_balances')
    op.drop_index(op.f('ix_leave_balances_company_id'), table_name='leave_balances')
    op.drop_table('leave_balances')
    op.drop_index(op.f('ix_employee_tax_profiles_employee_id'), table_name='employee_tax_profiles')
    op.drop_index(op.f('ix_employee_tax_profiles_company_id'), table_name='employee_tax_profiles')
    op.drop_table('employee_tax_profiles')
    op.drop_index(op.f('ix_tds_challans_company_id'), table_name='tds_challans')
    op.drop_table('tds_challans')
    op.drop_index(op.f('ix_salary_templates_company_id'), table_name='salary_templates')
    op.drop_index('idx_unique_template_name', table_name='salary_templates', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('salary_templates')
    op.drop_index(op.f('ix_payroll_cycles_company_id'), table_name='payroll_cycles')
    op.drop_table('payroll_cycles')
    op.drop_index(op.f('ix_leave_types_company_id'), table_name='leave_types')
    op.drop_table('leave_types')
    op.drop_index(op.f('ix_holidays_holiday_date'), table_name='holidays')
    op.drop_index(op.f('ix_holidays_company_id'), table_name='holidays')
    op.drop_table('holidays')
    op.drop_index(op.f('ix_payroll_audit_logs_created_at'), table_name='payroll_audit_logs')
    op.drop_index(op.f('ix_payroll_audit_logs_company_id'), table_name='payroll_audit_logs')
    op.drop_table('payroll_audit_logs')
    # ### end Alembic commands ###
