"""Add x360 models

Revision ID: b529f2160b35
Revises: 0c2e2cb37dbe
Create Date: 2026-03-27 14:34:08.198200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b529f2160b35'
down_revision: Union[str, None] = '0c2e2cb37dbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('x360_assessment_templates',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('x360_questions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('RATING', 'TEXT', name='questiontype'), nullable=False),
    sa.Column('category', sa.Enum('PERFORMANCE', 'ENGAGEMENT', 'CORE_VALUES', 'LEADERSHIP', name='questioncategory'), nullable=False),
    sa.Column('active_flag', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('x360_assessment_cycles',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'CLOSED', name='cyclestatus'), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['x360_assessment_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('x360_template_questions',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['x360_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['x360_assessment_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('template_id', 'question_id')
    )
    op.create_table('x360_assessment_assignments',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('ratee_id', sa.UUID(), nullable=False),
    sa.Column('rater_id', sa.UUID(), nullable=False),
    sa.Column('relation', sa.Enum('SELF', 'MANAGER', 'PEER', 'REPORT', name='relationtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', name='assignmentstatus'), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['x360_assessment_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ratee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rater_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('x360_employee_rater_maps',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('rater_employee_id', sa.UUID(), nullable=False),
    sa.Column('relation', sa.Enum('SELF', 'MANAGER', 'PEER', 'REPORT', name='relationtype'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rater_employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('x360_assessment_responses',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('answer_value', sa.Integer(), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['x360_assessment_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['x360_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('x360_assessment_responses')
    op.drop_table('x360_employee_rater_maps')
    op.drop_table('x360_assessment_assignments')
    op.drop_table('x360_template_questions')
    op.drop_table('x360_assessment_cycles')
    op.drop_table('x360_questions')
    op.drop_table('x360_assessment_templates')
    # ### end Alembic commands ###
