"""Add consultancy fields to company

Revision ID: f3c39a8fb140
Revises: fde36a920751
Create Date: 2026-04-16 11:00:42.326308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3c39a8fb140'
down_revision: Union[str, None] = 'fde36a920751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('is_consultancy', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('companies', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'companies', 'companies', ['parent_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('interview_attempts_company_id_fkey', 'interview_attempts', type_='foreignkey')
    op.create_foreign_key(None, 'interview_attempts', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('interview_automations_company_id_fkey', 'interview_automations', type_='foreignkey')
    op.create_foreign_key(None, 'interview_automations', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('interview_schedules_company_id_fkey', 'interview_schedules', type_='foreignkey')
    op.create_foreign_key(None, 'interview_schedules', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('interviews_company_id_fkey', 'interviews', type_='foreignkey')
    op.create_foreign_key(None, 'interviews', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    op.add_column('onboarding_activities', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'onboarding_activities', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('onboarding_documents_company_id_fkey', 'onboarding_documents', type_='foreignkey')
    op.create_foreign_key(None, 'onboarding_documents', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('onboarding_notes_company_id_fkey', 'onboarding_notes', type_='foreignkey')
    op.create_foreign_key(None, 'onboarding_notes', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('onboarding_tasks_company_id_fkey', 'onboarding_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'onboarding_tasks', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'onboarding_tasks', type_='foreignkey')
    op.create_foreign_key('onboarding_tasks_company_id_fkey', 'onboarding_tasks', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'onboarding_notes', type_='foreignkey')
    op.create_foreign_key('onboarding_notes_company_id_fkey', 'onboarding_notes', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'onboarding_documents', type_='foreignkey')
    op.create_foreign_key('onboarding_documents_company_id_fkey', 'onboarding_documents', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'onboarding_activities', type_='foreignkey')
    op.drop_column('onboarding_activities', 'company_id')
    op.drop_constraint(None, 'interviews', type_='foreignkey')
    op.create_foreign_key('interviews_company_id_fkey', 'interviews', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'interview_schedules', type_='foreignkey')
    op.create_foreign_key('interview_schedules_company_id_fkey', 'interview_schedules', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'interview_automations', type_='foreignkey')
    op.create_foreign_key('interview_automations_company_id_fkey', 'interview_automations', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'interview_attempts', type_='foreignkey')
    op.create_foreign_key('interview_attempts_company_id_fkey', 'interview_attempts', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_column('companies', 'parent_id')
    op.drop_column('companies', 'is_consultancy')
    # ### end Alembic commands ###
