"""add_multitenancy_isolation

Revision ID: fde36a920751
Revises: 12fac4e5a9b3
Create Date: 2026-04-15 15:08:54.388702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fde36a920751'
down_revision: Union[str, None] = '12fac4e5a9b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_automations', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'assessment_automations', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    op.add_column('assessment_templates', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'assessment_templates', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    op.add_column('candidate_applications', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'candidate_applications', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    op.add_column('candidates', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'candidates', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    op.add_column('onboarding_templates', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'onboarding_templates', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    op.add_column('onboardings', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'onboardings', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'onboardings', type_='foreignkey')
    op.drop_column('onboardings', 'company_id')
    op.drop_constraint(None, 'onboarding_templates', type_='foreignkey')
    op.drop_column('onboarding_templates', 'company_id')
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_column('candidates', 'company_id')
    op.drop_constraint(None, 'candidate_applications', type_='foreignkey')
    op.drop_column('candidate_applications', 'company_id')
    op.drop_constraint(None, 'assessment_templates', type_='foreignkey')
    op.drop_column('assessment_templates', 'company_id')
    op.drop_constraint(None, 'assessment_automations', type_='foreignkey')
    op.drop_column('assessment_automations', 'company_id')
    # ### end Alembic commands ###
