"""Guests — outside people who can see some of your jobs, and nothing else.

Two halves, deliberately separated:

  * `/guests/…` is the admin side. It needs the organization permission, and it is where guests
    are created, scoped, revoked and re-invited.
  * `/guest-portal/…` is what the guest actually uses. It takes a token instead of a login, and
    every one of its queries is filtered by that guest's scope rather than by a company id. That
    separation is the point: the portal has no code path that could return an out-of-scope
    record even if it were called with the wrong arguments, because scope is resolved from the
    token before anything is read.

Scope is Manatal's, exactly: a department, plus an access level of either "every job in that
department" or "only these named jobs". A guest with neither sees nothing, which is the right
default for a record that has just been created and not yet aimed at anything.

What a guest can see, in full: the jobs in scope, the candidates on those jobs, and each
candidate's name, experience, skills, stage and contact details. Not: other jobs, other candidates, notes,
salary, the pipeline of anyone they were not shown, or anything at all about the company beyond
its name. If it is not listed here it is not exposed, and the tests assert that by asking for
things a guest should not get.
"""

import secrets
import uuid
from datetime import UTC, datetime
from typing import Annotated, Any, Literal

from fastapi import APIRouter, Depends, HTTPException, Query
from pydantic import BaseModel, EmailStr, Field
from sqlalchemy import func, or_, select

from app.core.dependencies import DBSessionDep, PermissionChecker
from app.models.enterprise.candidate import Candidate, CandidateApplication
from app.models.enterprise.company import Company
from app.models.enterprise.guest import ACCESS_ALL_DEPARTMENT_JOBS, ACCESS_SPECIFIC_JOBS, Guest
from app.models.enterprise.job import JobRequirement
from app.models.shared.constants import ModuleScope, PermissionAction

router = APIRouter(prefix="/guests", tags=["Guests"])
portal = APIRouter(prefix="/guest-portal", tags=["Guest Portal"])


def _company(user: object) -> Any:
    cid = getattr(user, "company_id", None)
    if not cid:
        raise HTTPException(status_code=404, detail="No company on this account.")
    return cid


def _now() -> datetime:
    """Naive UTC — these columns are TIMESTAMP WITHOUT TIME ZONE."""
    return datetime.now(UTC).replace(tzinfo=None)


def _token() -> str:
    """32 bytes of randomness, hex-encoded.

    This is the whole credential, so it is generated by secrets rather than uuid4: a uuid is
    unique but not required to be unpredictable, and predictability is the only property that
    matters for something that grants access on its own.
    """
    return secrets.token_hex(32)


def _guest_out(g: Guest, *, with_token: bool = False) -> dict[str, Any]:
    out = {
        "id": str(g.id),
        "full_name": g.full_name,
        "display_name": g.display_name,
        "email": g.email,
        "phone": g.phone,
        "location": g.location,
        "description": g.description,
        "department": g.department,
        "access_level": g.access_level,
        "status": g.status,
        "jobs": [{"id": str(j.id), "title": j.title, "department": j.department} for j in g.jobs],
        "job_count": len(g.jobs),
        "invited_at": g.invited_at.isoformat() if g.invited_at else None,
        "last_seen_at": g.last_seen_at.isoformat() if g.last_seen_at else None,
        "created_at": g.created_at.isoformat() if g.created_at else None,
    }
    # The link is only handed back on create and on an explicit re-invite. A list endpoint that
    # returned every token would put working credentials for every guest into any log, browser
    # cache or screenshot of that page.
    if with_token:
        out["invite_token"] = g.invite_token
    return out


async def _load(session: DBSessionDep, cid: Any, guest_id: uuid.UUID) -> Guest:
    """One guest of this company, or 404 — never 403, which would confirm the id exists."""
    g = (
        await session.execute(
            select(Guest).where(Guest.id == guest_id, Guest.company_id == cid, Guest.deleted_at.is_(None))
        )
    ).scalar_one_or_none()
    if g is None:
        raise HTTPException(status_code=404, detail="Guest not found")
    return g


async def _resolve_jobs(session: DBSessionDep, cid: Any, job_ids: list[uuid.UUID]) -> list[JobRequirement]:
    if not job_ids:
        return []
    return list(
        (
            await session.execute(
                select(JobRequirement).where(
                    JobRequirement.id.in_(job_ids),
                    # Scoped on the way in. A valid job id from another company must never be
                    # attachable to a guest, or the scope check downstream is moot.
                    JobRequirement.company_id == cid,
                    JobRequirement.deleted_at.is_(None),
                )
            )
        )
        .scalars()
        .all()
    )


class GuestIn(BaseModel):
    full_name: str = Field(min_length=1, max_length=255)
    display_name: str | None = Field(default=None, max_length=255)
    email: EmailStr
    phone: str | None = Field(default=None, max_length=50)
    location: str | None = Field(default=None, max_length=255)
    description: str | None = None
    department: str | None = Field(default=None, max_length=255)
    access_level: Literal["all_department_jobs", "specific_jobs"] = ACCESS_ALL_DEPARTMENT_JOBS
    job_ids: list[uuid.UUID] = Field(default_factory=list, max_length=200)


def _validate_scope(body: GuestIn) -> None:
    """Refuse a scope that contradicts itself.

    A guest set to "all department jobs" with no department, or to "specific jobs" with no jobs,
    would save happily and then show nothing — and "the guest says they can't see anything" is a
    much worse bug to chase than a form that would not submit.
    """
    if body.access_level == ACCESS_ALL_DEPARTMENT_JOBS and not (body.department or "").strip():
        raise HTTPException(
            status_code=422, detail="Pick a department, or switch the access level to specific jobs."
        )
    if body.access_level == ACCESS_SPECIFIC_JOBS and not body.job_ids:
        raise HTTPException(status_code=422, detail="Choose at least one job to share.")


@router.get("")
async def list_guests(
    session: DBSessionDep,
    current_user: Annotated[
        object, Depends(PermissionChecker(ModuleScope.organization, PermissionAction.read))
    ],
    q: str | None = None,
    department: str | None = None,
    status: Literal["invited", "active", "revoked"] | None = None,
    page: int = Query(1, ge=1),
    page_size: int = Query(25, ge=1, le=100),
) -> dict[str, Any]:
    cid = _company(current_user)
    where = [Guest.company_id == cid, Guest.deleted_at.is_(None)]
    if q and q.strip():
        like = f"%{q.strip()}%"
        where.append(
            or_(Guest.full_name.ilike(like), Guest.display_name.ilike(like), Guest.email.ilike(like))
        )
    if department:
        where.append(Guest.department == department)
    if status:
        where.append(Guest.status == status)

    total = (await session.execute(select(func.count()).select_from(Guest).where(*where))).scalar_one()
    rows = (
        (
            await session.execute(
                select(Guest)
                .where(*where)
                .order_by(Guest.created_at.desc())
                .offset((page - 1) * page_size)
                .limit(page_size)
            )
        )
        .scalars()
        .unique()
        .all()
    )
    return {"total": total, "page": page, "page_size": page_size, "results": [_guest_out(g) for g in rows]}


@router.get("/scope-options")
async def scope_options(
    session: DBSessionDep,
    current_user: Annotated[
        object, Depends(PermissionChecker(ModuleScope.organization, PermissionAction.read))
    ],
) -> dict[str, Any]:
    """The departments and jobs a guest can be pointed at.

    Departments come from the jobs themselves rather than from a departments table. Croar stores
    a department as free text on a job, and separately has a departments table used by the HR
    side for employees; the two are unrelated. Reading the distinct values off jobs is the one
    that actually groups jobs today, and it avoids pre-empting a decision about which becomes
    canonical — a decision that touches employees, payroll and reporting.
    """
    cid = _company(current_user)
    depts = (
        (
            await session.execute(
                select(JobRequirement.department)
                .where(
                    JobRequirement.company_id == cid,
                    JobRequirement.deleted_at.is_(None),
                    JobRequirement.department.is_not(None),
                    JobRequirement.department != "",
                )
                .distinct()
                .order_by(JobRequirement.department)
            )
        )
        .scalars()
        .all()
    )
    jobs = (
        (
            await session.execute(
                select(JobRequirement)
                .where(JobRequirement.company_id == cid, JobRequirement.deleted_at.is_(None))
                .order_by(JobRequirement.created_at.desc())
                .limit(500)
            )
        )
        .scalars()
        .all()
    )
    return {
        "departments": list(depts),
        "jobs": [
            {"id": str(j.id), "title": j.title, "department": j.department, "location": j.location}
            for j in jobs
        ],
    }


@router.post("", status_code=201)
async def create_guest(
    body: GuestIn,
    session: DBSessionDep,
    current_user: Annotated[
        object, Depends(PermissionChecker(ModuleScope.organization, PermissionAction.create))
    ],
) -> dict[str, Any]:
    cid = _company(current_user)
    _validate_scope(body)
    email = body.email.strip().lower()

    clash = (
        await session.execute(
            select(Guest).where(Guest.company_id == cid, Guest.email == email, Guest.deleted_at.is_(None))
        )
    ).scalar_one_or_none()
    if clash:
        raise HTTPException(status_code=409, detail=f"{email} is already a guest here.")

    g = Guest(
        full_name=body.full_name.strip(),
        display_name=(body.display_name or body.full_name).strip(),
        email=email,
        phone=(body.phone or "").strip() or None,
        location=(body.location or "").strip() or None,
        description=(body.description or "").strip() or None,
        department=(body.department or "").strip() or None,
        access_level=body.access_level,
        status="invited",
        invite_token=_token(),
        invited_at=_now(),
        company_id=cid,
        created_by=getattr(current_user, "id", None),
    )
    if body.access_level == ACCESS_SPECIFIC_JOBS:
        g.jobs = await _resolve_jobs(session, cid, body.job_ids)
        if not g.jobs:
            raise HTTPException(status_code=422, detail="None of those jobs belong to this account.")
    session.add(g)
    await session.commit()
    await session.refresh(g)
    return _guest_out(g, with_token=True)


@router.patch("/{guest_id}")
async def update_guest(
    guest_id: uuid.UUID,
    body: GuestIn,
    session: DBSessionDep,
    current_user: Annotated[
        object, Depends(PermissionChecker(ModuleScope.organization, PermissionAction.update))
    ],
) -> dict[str, Any]:
    cid = _company(current_user)
    g = await _load(session, cid, guest_id)
    _validate_scope(body)
    email = body.email.strip().lower()
    if email != g.email:
        clash = (
            await session.execute(
                select(Guest).where(
                    Guest.company_id == cid,
                    Guest.email == email,
                    Guest.id != g.id,
                    Guest.deleted_at.is_(None),
                )
            )
        ).scalar_one_or_none()
        if clash:
            raise HTTPException(status_code=409, detail=f"{email} is already a guest here.")

    g.full_name = body.full_name.strip()
    g.display_name = (body.display_name or body.full_name).strip()
    g.email = email
    g.phone = (body.phone or "").strip() or None
    g.location = (body.location or "").strip() or None
    g.description = (body.description or "").strip() or None
    g.department = (body.department or "").strip() or None
    g.access_level = body.access_level
    # Narrowing to a department must drop the named jobs, or a later widening would silently
    # restore a list nobody remembers agreeing to.
    g.jobs = (
        await _resolve_jobs(session, cid, body.job_ids) if body.access_level == ACCESS_SPECIFIC_JOBS else []
    )
    if body.access_level == ACCESS_SPECIFIC_JOBS and not g.jobs:
        raise HTTPException(status_code=422, detail="None of those jobs belong to this account.")
    await session.commit()
    await session.refresh(g)
    return _guest_out(g)


@router.post("/{guest_id}/revoke")
async def revoke_guest(
    guest_id: uuid.UUID,
    session: DBSessionDep,
    current_user: Annotated[
        object, Depends(PermissionChecker(ModuleScope.organization, PermissionAction.update))
    ],
) -> dict[str, Any]:
    """Kill the link. The record stays so you can see who had access and when."""
    cid = _company(current_user)
    g = await _load(session, cid, guest_id)
    g.status = "revoked"
    await session.commit()
    return _guest_out(g)


@router.post("/{guest_id}/reinvite")
async def reinvite_guest(
    guest_id: uuid.UUID,
    session: DBSessionDep,
    current_user: Annotated[
        object, Depends(PermissionChecker(ModuleScope.organization, PermissionAction.update))
    ],
) -> dict[str, Any]:
    """Issue a fresh link, which invalidates the old one.

    Re-inviting rotates the token rather than reusing it. If a link was forwarded to the wrong
    person, "send it again" has to be the thing that locks them out, not the thing that gives
    them a second copy.
    """
    cid = _company(current_user)
    g = await _load(session, cid, guest_id)
    g.invite_token = _token()
    g.status = "invited"
    g.invited_at = _now()
    g.last_seen_at = None
    await session.commit()
    await session.refresh(g)
    return _guest_out(g, with_token=True)


@router.delete("/{guest_id}", status_code=204)
async def delete_guest(
    guest_id: uuid.UUID,
    session: DBSessionDep,
    current_user: Annotated[
        object, Depends(PermissionChecker(ModuleScope.organization, PermissionAction.delete))
    ],
) -> None:
    cid = _company(current_user)
    g = await _load(session, cid, guest_id)
    g.deleted_at = _now()
    # Revoked as well as deleted. A soft delete that left the token live would be a guest who
    # has vanished from the list and can still read the pipeline.
    g.status = "revoked"
    await session.commit()


# ───────────────────────────── the guest's own view ──────────────────────────


async def _guest_by_token(session: DBSessionDep, token: str) -> Guest:
    g = (
        await session.execute(select(Guest).where(Guest.invite_token == token, Guest.deleted_at.is_(None)))
    ).scalar_one_or_none()
    # One message for "no such link" and "revoked link" alike. Telling the holder of a dead
    # token that it used to be valid confirms the account exists and invites retries.
    if g is None or g.status == "revoked":
        raise HTTPException(status_code=404, detail="This link is no longer valid.")
    return g


async def _jobs_in_scope(session: DBSessionDep, g: Guest) -> list[JobRequirement]:
    """Exactly the jobs this guest may see. Every portal read goes through here."""
    if g.access_level == ACCESS_SPECIFIC_JOBS:
        return [j for j in g.jobs if j.deleted_at is None]
    if not g.department:
        return []
    return list(
        (
            await session.execute(
                select(JobRequirement)
                .where(
                    JobRequirement.company_id == g.company_id,
                    JobRequirement.department == g.department,
                    JobRequirement.deleted_at.is_(None),
                )
                .order_by(JobRequirement.created_at.desc())
            )
        )
        .scalars()
        .all()
    )


@portal.get("/{token}")
async def portal_home(token: str, session: DBSessionDep) -> dict[str, Any]:
    """What the guest sees when they open their link: who invited them, and their jobs."""
    g = await _guest_by_token(session, token)
    if g.status == "invited":
        g.status = "active"
    g.last_seen_at = _now()
    await session.commit()

    company = (await session.execute(select(Company).where(Company.id == g.company_id))).scalar_one_or_none()
    jobs = await _jobs_in_scope(session, g)

    counts = {}
    if jobs:
        rows = (
            await session.execute(
                select(CandidateApplication.job_requirement_id, func.count())
                .where(CandidateApplication.job_requirement_id.in_([j.id for j in jobs]))
                .group_by(CandidateApplication.job_requirement_id)
            )
        ).all()
        counts = dict(rows)

    return {
        "guest": {"display_name": g.display_name, "department": g.department, "access_level": g.access_level},
        "company": {"name": getattr(company, "name", None)},
        "jobs": [
            {
                "id": str(j.id),
                "title": j.title,
                "department": j.department,
                "location": j.location,
                "candidate_count": counts.get(j.id, 0),
            }
            for j in jobs
        ],
    }


@portal.get("/{token}/jobs/{job_id}/candidates")
async def portal_candidates(token: str, job_id: uuid.UUID, session: DBSessionDep) -> dict[str, Any]:
    """The candidates on one job the guest may see.

    The job is checked against the guest's scope rather than against a company id. A guest of
    the right company but the wrong department gets the same 404 as a stranger, because the
    question being asked is "may THIS guest see THIS job", and company membership does not
    answer it.
    """
    g = await _guest_by_token(session, token)
    jobs = await _jobs_in_scope(session, g)
    job = next((j for j in jobs if j.id == job_id), None)
    if job is None:
        raise HTTPException(status_code=404, detail="Job not found")

    rows = (
        await session.execute(
            select(Candidate, CandidateApplication)
            .join(CandidateApplication, CandidateApplication.candidate_id == Candidate.id)
            .where(CandidateApplication.job_requirement_id == job_id, Candidate.deleted_at.is_(None))
            .order_by(CandidateApplication.created_at.desc())
        )
    ).all()

    return {
        "job": {"id": str(job.id), "title": job.title, "department": job.department},
        # Deliberately narrow. A guest gets who applied and where they are in the process —
        # not notes, not salary, not the AI scoring, and nothing about anyone on another job.
        "candidates": [
            {
                "id": str(c.id),
                "full_name": c.full_name,
                # Candidate has no headline column; years and skills are what a hiring manager
                # actually scans a shortlist for anyway.
                "total_experience": c.total_experience,
                "skills": c.skills or [],
                "email": c.email,
                "phone": c.phone,
                "status_id": a.status_id,
                "applied_at": a.created_at.isoformat() if a.created_at else None,
            }
            for c, a in rows
        ],
    }
